name: GitHub Pages Deployment

on:
  push:
    branches:
      - main # Adjust if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Adjust as needed

      - name: Install dependencies
        run: npm install # Or any other commands to install dependencies

      - name: Build site
        run: npm run build # Or any other build commands

      - name: Report build status
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const { context, GitHub } = require('@actions/github');
            const octokit = new GitHub(process.env.GITHUB_TOKEN);
            const githubContext = context;

            octokit.repos.createCommitStatus({
              owner: githubContext.repo.owner,
              repo: githubContext.repo.repo,
              sha: githubContext.sha,
              state: 'success',
              context: 'GitHub Pages Deployment',
              target_url: 'https://github.com/yourusername/yourrepository/actions/runs/' + process.env.GITHUB_RUN_ID,
              description: 'Deployment successful'
            });

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./ # Publishes the entire repository content
