name: GitHub Pages Deployment

on:
  push:
    branches:
      - main # Adjust if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Adjust as needed

      - name: Install dependencies
        run: npm install # Or any other commands to install dependencies

      - name: Build site
        run: npm run build # Or any other build commands

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build # Adjust the directory where your built site is located
